# This script is just a demo where we will explain variables.

# Load modules
import-module MSAL.PS
import-module '.\loadme.psd1'

# Create a bunch of new variables with all environment variable wich start with a specific prefix. Bydefault ___ (3 underscores)
New-VariableFactoryFromEnvVariable

# Let's see the current the variables
Write-host "Current session variables are:"

Get-Variable

# Now for fun let's add a new variable prefixes with '___' (by default)
Write-host ""
Write-host "Let's now create a new variable prefixes with ___"

New-Variable -Name '___NewVarFromContainer' -Value 'Hi from container'

Write-host ""
Write-host "Let's now create a an hashtable from prefixes variables"
# Let's circle back where we grab all variables with a specific prefix (by default ___) and convert it into an hashtable
$Data = New-HashtableFactory

Write-host ""
Write-host "The hashtable provided is:"

$Data

# Then we trigger a new HTTP Az function and provide all our filtered variable to store this info somewhere else (in this case another Q)
# In our case, the $___NextStageFunctionUrl has been generated by the New-VariableFactoryFromEnvVariable function because this key has been provided in the previous Q.
Invoke-RestMethod -Method Post -Uri $___NextStageFunctionUrl -Body $(ConvertTo-Json $data -Depth 99)

